### ISSUE TITLE
Error Decoding

### ISSUE THREAD

**Issue by antoniomartin2** [sparkfish/pdf417decoder#1]
Whenever I try to run the decoder.decode() dommand, I get the following error. Do you have any suggestions? Thanks!

UnboundLocalError: local variable 'codewords_ptr' referenced before assignment

**Comment by tbrettallen** [comment]
Are you able to send me the barcode you're using please?

**Comment by antoniomartin2** [comment]
[Antonio Martin.pdf](https://github.com/sparkfish/pdf417decoder/files/6275658/Antonio.Martin.pdf)

Here is an example, I want to read the PDF417 code on it. I rotated the image so that the barcode has a horizontal orientation. The image with the barcode contains the whole FedEx label.

**Comment by tbrettallen** [comment]
Thank you! I've been able to reproduce the error. I'll let you know when it's fixed!

**Comment by tbrettallen** [comment]
I've committed the code to fix this and have updated the package on PyPI.

If you're using the package, go ahead and upgrade to version 1.0.3 to use the latest code.

Can you confirm this fixed the issue for you so I can close this out?

**Comment by antoniomartin2** [comment]
Even when oriented vertically, I am getting zero barcodes detected in the image. The codewords_ptr issue is resolved, however now barcodes are not detected. My png file is attached for reference.

`Python 3.9.0+ (default, Oct 20 2020, 08:43:38)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pdf417decoder import PDF417Decoder
>>> from PIL import Image
>>> img = Image.open('img.png')
>>> decoder = PDF417Decoder(img)
>>> decoder.decode()
0
>>>`

<img width="336" alt="img" src="https://user-images.githubusercontent.com/11871695/114071234-e45c2280-986e-11eb-9ffe-5d7f74750aaf.png">

**Comment by antoniomartin2** [comment]
By the way, not sure if you noticed this, but in the Decoder file, at least in 1.0.2, you did not account for the possibility that an image was already black and white, causing the code to crash when I attempted to load an already black and white image (the CV2 conversion to grayscale raised an error.

**Comment by tbrettallen** [comment]
Low resolution images will fail to detect a barcode. That is an issue with the original C# version created by Uzi as well. I ran across that issue as well with your sample and then zoomed in to the PDF to get a higher resolution image of it.

As for the black and white version causing the code to crash, I will add that to the todo list to fix. Thank you for pointing that out!

**Comment by tbrettallen** [comment]
Here is the original C# version that this library is based on in case you're interested: https://www.codeproject.com/Articles/4042463/PDF417-Barcode-Decoder-NET-Class-Library-and-Two-D

**Comment by antoniomartin2** [comment]
Thanks! So, I should try to make the image higher resolution for it to be decoded?

**Comment by antoniomartin2** [comment]
`    def convert_image(self) -> bool:
        """ Convert image to black and white boolean matrix """
        self.image_width = self.input_image.width
        self.image_height = self.input_image.height

        np_image = np.array(self.input_image)
        if len(np_image.shape) >= 3:
            gray = cv2.cvtColor(np_image, cv2.COLOR_BGR2GRAY)
        else:
            gray = np_image
        black_white = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]`

This code fixes the BW issue!

**Comment by tbrettallen** [comment]
Correct, I was able to decode the barcode you gave me when I increased the resolution.

Thanks for the fix, I'll apply that when I get a chance!

**Comment by tbrettallen** [comment]
Did you mean

        np_image = np.array(self.input_image)
        if (np_image.shape[2] >= 3):
            gray = cv2.cvtColor(np_image, cv2.COLOR_BGR2GRAY)
        else:
            gray = np_image
        black_white = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

The len of np_image.shape would always be 3 (height, width, color depth). Color depth should be the one to check right?

**Comment by tbrettallen** [comment]
Fix and grayscale check was added to version 1.0.4
