### ISSUE TITLE
Unable to install pdf417decoder

### ISSUE THREAD

**Issue by hassanahmed95** [sparkfish/pdf417decoder#3]
I am trying to install pdf417decoder. I am using command:
pip install pdf417decoder
but everytime I get following error :
ERROR: Could not find a version that satisfies the requirement pdf417decoder (from versions: none)
ERROR: No matching distribution found for pdf417decoder

Can you please help me out to install the package

**Comment by jboarman** [comment]
@hassanahmed95 From the setup requirements, the package currently requires python version ">=3.7".  Can you confirm what version of Python you are running now?

**Comment by hassanahmed95** [comment]
@jboarman I am using Python version 3.6.9. I have constraint of using that version of Python. Is it possible to use pdf417decoder with Python version 3.6.9 ?

**Comment by tbrettallen** [comment]
> @jboarman I am using Python version 3.6.9. I have constraint of using that version of Python. Is it possible to use pdf417decoder with Python version 3.6.9 ?

We've only tested it against 3.7. You can try downloading the code from the repo directly and see if it will run with the 3.6.9 environment but we can't guarantee it will.

Let us know if it works, thanks!

**Comment by jboarman** [comment]
It seems that NumPy v1.20.1 requires Python 3.7.  So, it would depend if an older version of NumPy can be used.

**Comment by jboarman** [comment]
@hassanahmed95 Do you mind pulling down the code and trying NumPy 1.19.5?  If it works, then do a pull request and you will be an official contributor to the package!  :)

https://pypi.org/project/numpy/1.19.5/

**Comment by proofconstruction** [comment]
@hassanahmed95 Were you able to get this working with an older version of NumPy?

**Comment by jboarman** [comment]
As Python 3.6 reached its end-of-life phase as of [2021-12-23](https://peps.python.org/pep-0494/), this issue is being closed as "obsolete",
