### ISSUE TITLE
Mac Users -- pdf417decoder crashes upon import, with fix

### ISSUE THREAD

**Issue by adammbaker** [sparkfish/pdf417decoder#4]
Reading through the stack trace it appears it's looking for `ffmpeg`.

I don't know if this is something that can be fixed in this repo/library but I figured I'd report it so that it's known and what the fix is.

# Issue
Computer: Apple MacBook Pro 16" with Apple Silicon M1
Running Python 3.9.6 in Terminal.app

```bash
>>> import pdf417decoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python3.9/site-packages/pdf417decoder/__init__.py", line 1, in <module>
    from pdf417decoder.Decoder import PDF417Decoder
  File "/python3.9/site-packages/pdf417decoder/Decoder.py", line 4, in <module>
    import cv2
  File "/python3.9/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: dlopen(/python3.9/site-packages/cv2/cv2.cpython-39-darwin.so, 2): Library not loaded: /opt/homebrew/opt/ffmpeg/lib/libavcodec.58.dylib
  Referenced from: /python3.9/site-packages/cv2/cv2.cpython-39-darwin.so
  Reason: image not found
```

# Fix

I installed `ffmpeg` through Homebrew and it ran fine.

**Comment by jboarman** [comment]
Thanks @adammbaker for identify an issue and its resolution.

From what I'm reading online for Mac users, either of these could work:  `brew install ffmpeg`  or even  `brew install opencv`
