### ISSUE TITLE
Cannot decode barcodes which are not padded

### ISSUE THREAD

**Issue by ihabunek** [sparkfish/pdf417decoder#6]
I noticed that barcodes which don't have any padding cannot be decoded. I'm using the following code to test:

```py
import sys
from PIL import Image
from pdf417decoder import PDF417Decoder

image = Image.open(sys.argv[1])
decoder = PDF417Decoder(image)

if decoder.decode() > 0:
    decoded = decoder.barcode_data_index_to_string(0)
    print(decoded)
else:
    print("cannot decode")
```

The following image cannot be decoded:
![invalid](https://user-images.githubusercontent.com/482138/177003401-2e5803a4-f68c-4d13-9e31-e580aa23dfe8.png)

While the following image can:
![valid](https://user-images.githubusercontent.com/482138/177003407-ada754da-4667-478e-b4e2-dc951eb8525a.png)

Images are the same, except that second image has 1px of white padding around the barcode, while the first image touches the image borders.

**Comment by jboarman** [comment]
Hi Ivan, would you be open to submitting a pull request that adds a 1px border to incoming images to resolve this issue?  

We'll merge your PR and can release an update that has that fix incorporated.

**Comment by kwcckw** [comment]
I added the padding here : https://github.com/sparkfish/pdf417decoder/pull/7

Looks like the left most of the image need to have single white line , otherwise the start-stop signature won't be detected and hence no barcode will be detected.

**Comment by ghost** [comment]
This should be closed then right?

**Comment by kwcckw** [comment]
> This should be closed then right?

It should be resolved, did you facing any problem with it?

**Comment by ghost** [comment]
I didn't I was just researching and found the open issue, and I think I
found a commit or a pull request somewhere that fixes it

**Comment by kwcckw** [comment]
Yes, this pull request should be merged now:
https://github.com/sparkfish/pdf417decoder/pull/7

**Comment by ghost** [comment]
> Yes, this pull request should be merged now:
> https://github.com/sparkfish/pdf417decoder/pull/7

Awesome, let's close this issue then 🙏
